//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlPractice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public System.Guid RecId { get; set; }
        public string Serial { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string Publisher { get; set; }
        public string NewsImagePath { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
